language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - qmake
  - make
  - ./tests/tests
# Codecov
  - ./get_code_cov.sh
  - codecov

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*" -E ".*tests/.*.h.*"

notifications:
  email: false
