language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - qmake -project
  - make
  - ./tests/tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"

notifications:
  email: false
