name: CI/CD GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule init
      - run: git submodule update
      - run: pip install --user cpp-coveralls
      - run: sudo apt install -y qt5-qmake qt5-default
      - run: qmake
      - run: make
      - run: ./tests/tests

      - name: Coveralls
        run: coveralls --root . -E ".*external.*" -E ".*tests.*"
